name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build (CI uses dev alias)
        run: npm run dev
        env:
          # These are provided on GitHub-hosted runners
          GITHUB_ACTIONS: true
          GITHUB_REPOSITORY: ${{ github.repository }}
          # Set absolute base URL only for GitHub Pages deploy
          DEPLOY_BASE: https://claserre9.github.io/vite-quiz-game/

      - name: Verify build output
        run: |
          test -d dist || { echo "dist not found"; exit 1; }
          test -f dist/index.html || { echo "dist/index.html not found"; exit 1; }
          ls -la dist

      - name: Add SPA fallback (copy index.html to 404.html)
        run: cp dist/index.html dist/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
